/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Administrator;
import modelo.Appointment;
import modelo.AppointmentStatus;
import modelo.Doctor;
import modelo.Hospitalization;
import modelo.HospitalizationStatus;
import modelo.Patient;
import modelo.Prescription;
import modelo.RoomType;
import modelo.Specialty;
import modelo.User;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class DoctorView extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private ArrayList<Hospitalization>hospitalizations;
    private ArrayList<Appointment>appointments;
    private Doctor doctor;
    private Patient patient;
    
    public DoctorView(User user,Doctor doc, ArrayList<User> users,ArrayList<Hospitalization> hospitalizations,ArrayList<Appointment> appointments) {
        initComponents();
        this.user = user;
        this.users = users;
        this.doctor = doc;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        if (user instanceof Administrator)
            BackButton.setVisible(true);
        else    
            BackButton.setVisible(false);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }
    
    private LoginController createLoginController() {
        LoginController loginController = new LoginController(users, appointments, hospitalizations);
        return loginController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutPanelRound = new packagee.PanelRound();
        SuperiorPanelRound = new packagee.PanelRound();
        ExitButtonDoctorView = new javax.swing.JButton();
        DoctorViewLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        DoctorViewTabbedPane = new javax.swing.JTabbedPane();
        AppointmentsVisualizationPanel = new javax.swing.JPanel();
        TotalAppointmentsRadioButton = new javax.swing.JRadioButton();
        AppointmentsVisualizationScrollPane = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        PendingAppointmentsRadioButton = new javax.swing.JRadioButton();
        LogoutButton = new javax.swing.JButton();
        HistoryAppointmentsPatientPanel = new javax.swing.JPanel();
        PatientComboBox = new javax.swing.JComboBox<>();
        PatientLabel = new javax.swing.JLabel();
        HistoryAppointmentsPatientScrollPane = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        SearchButton = new javax.swing.JButton();
        ModifyInfoPanel = new javax.swing.JPanel();
        FirstnameLabel = new javax.swing.JLabel();
        FirstnameTextField = new javax.swing.JTextField();
        LastnameLabel = new javax.swing.JLabel();
        LastnameTextField = new javax.swing.JTextField();
        SpecialtyLabel = new javax.swing.JLabel();
        LicenseNumberLabel = new javax.swing.JLabel();
        LicenseNumberTextField = new javax.swing.JTextField();
        AssignedOfficeLabel = new javax.swing.JLabel();
        UserTextField = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        AssignedOfficeTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordConfirmLabel = new javax.swing.JLabel();
        PasswordConfirmTextField = new javax.swing.JTextField();
        SpecialtyComboBox = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        RequestAppointmentsPanel = new javax.swing.JPanel();
        AppointmentIDLabel = new javax.swing.JLabel();
        AcceptMedicalAppointmentLabel = new javax.swing.JLabel();
        AppointmentIDComboBox = new javax.swing.JComboBox<>();
        Separator_Accept_Reschedule = new javax.swing.JSeparator();
        AcceptAppointment_AcceptButton = new javax.swing.JButton();
        RescheduleMedicalAppointmentLabel = new javax.swing.JLabel();
        Reschedule_AppointmentLabel = new javax.swing.JLabel();
        Reschedule_AppointmentComboBox = new javax.swing.JComboBox<>();
        RescheduleAppointment_AcceptButton = new javax.swing.JButton();
        NewTimeAppointmentLabel = new javax.swing.JLabel();
        NewTimeAppointTextField = new javax.swing.JTextField();
        ReasonForAppointmentLabel = new javax.swing.JLabel();
        ReasonAppointmentTextField = new javax.swing.JTextField();
        Separator_Reschedule_Complete = new javax.swing.JSeparator();
        CompleteMedicalAppointmentLabel = new javax.swing.JLabel();
        Complete_AppointmentLabel = new javax.swing.JLabel();
        Complete_AppointmentComboBox = new javax.swing.JComboBox<>();
        DiagnosisLabel = new javax.swing.JLabel();
        Complete_ObservationsLabel = new javax.swing.JLabel();
        RecommendTreatmentLabel = new javax.swing.JLabel();
        FollowUpIndicationLabel = new javax.swing.JLabel();
        CompleteButton = new javax.swing.JButton();
        HospitalizationLabel = new javax.swing.JLabel();
        ReasonForHospitalizationLabel = new javax.swing.JLabel();
        DateOfEntryLabel = new javax.swing.JLabel();
        DateOfEntryTextField = new javax.swing.JTextField();
        EstimatedDurationLabel = new javax.swing.JLabel();
        EstimatedDurationTextField = new javax.swing.JTextField();
        Hospitalization_ObservationsLabel = new javax.swing.JLabel();
        Hospitalization_ObservationsScrollPane = new javax.swing.JScrollPane();
        Hospitalization_ObservationsTextArea = new javax.swing.JTextArea();
        GenerateButton = new javax.swing.JButton();
        RequestsComboBox = new javax.swing.JComboBox<>();
        RequestsRadioButton = new javax.swing.JRadioButton();
        PatientIDRadioButton = new javax.swing.JRadioButton();
        DiagnosisScrollPane = new javax.swing.JScrollPane();
        DiagnosisTextArea = new javax.swing.JTextArea();
        ObservationsScrollPane = new javax.swing.JScrollPane();
        ObservationsTextArea = new javax.swing.JTextArea();
        RecommendedTreatmentScrollPane = new javax.swing.JScrollPane();
        RecommendedTreatmentTextArea = new javax.swing.JTextArea();
        FollowUpIndicationScrollPane = new javax.swing.JScrollPane();
        FollowUpIndicationTextArea = new javax.swing.JTextArea();
        Separator_Complete_ = new javax.swing.JSeparator();
        CancelButton = new javax.swing.JButton();
        RequestAppointment_PatientIDComboBox = new javax.swing.JComboBox<>();
        ReasonForHospitalizationScrollPane = new javax.swing.JScrollPane();
        ReasonForHospitalizationTextArea = new javax.swing.JTextArea();
        PrescribeMedicationsPanel = new javax.swing.JPanel();
        PrescribeMedication_AppointmentIDLabel = new javax.swing.JLabel();
        MedicationNameLabel = new javax.swing.JLabel();
        MedicationNameTextField = new javax.swing.JTextField();
        DoseLabel = new javax.swing.JLabel();
        DoseTextField = new javax.swing.JTextField();
        AdministrationRouteLabel = new javax.swing.JLabel();
        AdministrationRouteTextField = new javax.swing.JTextField();
        FrecuencyLabel = new javax.swing.JLabel();
        FrecuencyTextField = new javax.swing.JTextField();
        TreatmentDurationLabel = new javax.swing.JLabel();
        TreatmentDurationTextField = new javax.swing.JTextField();
        AdditionalInstructionsLabel = new javax.swing.JLabel();
        AdditionalInstructionsTextField = new javax.swing.JTextField();
        PrescribeMedicationsScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        PrescribeButton = new javax.swing.JButton();
        PrescribeMedication_AppointmentIDComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LayoutPanelRound.setRadius(50);

        SuperiorPanelRound.setRadius(50);
        SuperiorPanelRound.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SuperiorPanelRoundMouseDragged(evt);
            }
        });
        SuperiorPanelRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SuperiorPanelRoundMousePressed(evt);
            }
        });

        ExitButtonDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ExitButtonDoctorView.setText("X");
        ExitButtonDoctorView.setBorderPainted(false);
        ExitButtonDoctorView.setContentAreaFilled(false);
        ExitButtonDoctorView.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitButtonDoctorView.setFocusable(false);
        ExitButtonDoctorView.setRequestFocusEnabled(false);
        ExitButtonDoctorView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonDoctorViewActionPerformed(evt);
            }
        });

        DoctorViewLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        DoctorViewLabel.setText("DOCTOR VIEW");

        BackButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuperiorPanelRoundLayout = new javax.swing.GroupLayout(SuperiorPanelRound);
        SuperiorPanelRound.setLayout(SuperiorPanelRoundLayout);
        SuperiorPanelRoundLayout.setHorizontalGroup(
            SuperiorPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorPanelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoctorViewLabel)
                .addGap(32, 32, 32)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButtonDoctorView)
                .addGap(19, 19, 19))
        );
        SuperiorPanelRoundLayout.setVerticalGroup(
            SuperiorPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ExitButtonDoctorView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DoctorViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BackButton))
        );

        TotalAppointmentsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        TotalAppointmentsRadioButton.setText("Total appointments");
        TotalAppointmentsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalAppointmentsRadioButtonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        AppointmentsVisualizationScrollPane.setViewportView(jTable2);

        PendingAppointmentsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PendingAppointmentsRadioButton.setText("Pending appointments");
        PendingAppointmentsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingAppointmentsRadioButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AppointmentsVisualizationPanelLayout = new javax.swing.GroupLayout(AppointmentsVisualizationPanel);
        AppointmentsVisualizationPanel.setLayout(AppointmentsVisualizationPanelLayout);
        AppointmentsVisualizationPanelLayout.setHorizontalGroup(
            AppointmentsVisualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentsVisualizationPanelLayout.createSequentialGroup()
                .addGroup(AppointmentsVisualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoutButton)
                    .addGroup(AppointmentsVisualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AppointmentsVisualizationPanelLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(TotalAppointmentsRadioButton)
                            .addGap(18, 18, 18)
                            .addComponent(PendingAppointmentsRadioButton))
                        .addGroup(AppointmentsVisualizationPanelLayout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(AppointmentsVisualizationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        AppointmentsVisualizationPanelLayout.setVerticalGroup(
            AppointmentsVisualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentsVisualizationPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(AppointmentsVisualizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalAppointmentsRadioButton)
                    .addComponent(PendingAppointmentsRadioButton))
                .addGap(18, 18, 18)
                .addComponent(AppointmentsVisualizationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(23, 23, 23))
        );

        DoctorViewTabbedPane.addTab("Appointments visualization", AppointmentsVisualizationPanel);

        PatientComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        PatientLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientLabel.setText("Patient");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HistoryAppointmentsPatientScrollPane.setViewportView(jTable3);

        SearchButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HistoryAppointmentsPatientPanelLayout = new javax.swing.GroupLayout(HistoryAppointmentsPatientPanel);
        HistoryAppointmentsPatientPanel.setLayout(HistoryAppointmentsPatientPanelLayout);
        HistoryAppointmentsPatientPanelLayout.setHorizontalGroup(
            HistoryAppointmentsPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryAppointmentsPatientPanelLayout.createSequentialGroup()
                .addGroup(HistoryAppointmentsPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistoryAppointmentsPatientPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(PatientLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HistoryAppointmentsPatientPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(HistoryAppointmentsPatientScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryAppointmentsPatientPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SearchButton)
                .addGap(601, 601, 601))
        );
        HistoryAppointmentsPatientPanelLayout.setVerticalGroup(
            HistoryAppointmentsPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryAppointmentsPatientPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(HistoryAppointmentsPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientLabel)
                    .addComponent(PatientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(HistoryAppointmentsPatientScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(SearchButton)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        DoctorViewTabbedPane.addTab("History Appointments of a patient", HistoryAppointmentsPatientPanel);

        FirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FirstnameLabel.setText("Firstname");

        FirstnameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        LastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LastnameLabel.setText("Lastname");

        LastnameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SpecialtyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SpecialtyLabel.setText("Specialty");

        LicenseNumberLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LicenseNumberLabel.setText("License Number");

        LicenseNumberTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AssignedOfficeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AssignedOfficeLabel.setText("Assigned office");

        UserTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        UserLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserLabel.setText("User");

        AssignedOfficeTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswordTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText("Password");

        PasswordConfirmLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswordConfirmLabel.setText("Password confirmation");

        PasswordConfirmTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        SaveButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModifyInfoPanelLayout = new javax.swing.GroupLayout(ModifyInfoPanel);
        ModifyInfoPanel.setLayout(ModifyInfoPanelLayout);
        ModifyInfoPanelLayout.setHorizontalGroup(
            ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(FirstnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LastnameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SpecialtyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(SpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(LicenseNumberLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LicenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AssignedOfficeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AssignedOfficeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(UserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(PasswordConfirmLabel))
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(SaveButton))
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(PasswordConfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        ModifyInfoPanelLayout.setVerticalGroup(
            ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstnameLabel)
                    .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastnameLabel)
                    .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecialtyLabel)
                    .addComponent(SpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseNumberLabel)
                    .addComponent(LicenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssignedOfficeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssignedOfficeLabel))
                .addGap(30, 30, 30)
                .addComponent(UserLabel)
                .addGap(18, 18, 18)
                .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addGap(27, 27, 27)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordConfirmLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswordConfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(SaveButton)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        DoctorViewTabbedPane.addTab("Modify info", ModifyInfoPanel);

        AppointmentIDLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppointmentIDLabel.setText("Appointment ID");

        AcceptMedicalAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AcceptMedicalAppointmentLabel.setText("Accept medical appointment");

        AppointmentIDComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        Separator_Accept_Reschedule.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AcceptAppointment_AcceptButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AcceptAppointment_AcceptButton.setText("Accept");
        AcceptAppointment_AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptAppointment_AcceptButtonActionPerformed(evt);
            }
        });

        RescheduleMedicalAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RescheduleMedicalAppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RescheduleMedicalAppointmentLabel.setText("Reschedule medical appointment");

        Reschedule_AppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Reschedule_AppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reschedule_AppointmentLabel.setText("Appointment");

        Reschedule_AppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Reschedule_AppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        RescheduleAppointment_AcceptButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RescheduleAppointment_AcceptButton.setText("Accept");
        RescheduleAppointment_AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RescheduleAppointment_AcceptButtonActionPerformed(evt);
            }
        });

        NewTimeAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        NewTimeAppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewTimeAppointmentLabel.setText("New time appointment");

        NewTimeAppointTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        ReasonForAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReasonForAppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReasonForAppointmentLabel.setText("Reason for appointment");

        ReasonAppointmentTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        Separator_Reschedule_Complete.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CompleteMedicalAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CompleteMedicalAppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompleteMedicalAppointmentLabel.setText("Complete medical appointment");

        Complete_AppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Complete_AppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Complete_AppointmentLabel.setText("Appointment");

        Complete_AppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Complete_AppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        DiagnosisLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DiagnosisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiagnosisLabel.setText("Diagnosis");

        Complete_ObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Complete_ObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Complete_ObservationsLabel.setText("Observations");

        RecommendTreatmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RecommendTreatmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecommendTreatmentLabel.setText("Recommended treatment");

        FollowUpIndicationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FollowUpIndicationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FollowUpIndicationLabel.setText("Follow-up indication");

        CompleteButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CompleteButton.setText("Complete");
        CompleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteButtonActionPerformed(evt);
            }
        });

        HospitalizationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospitalizationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospitalizationLabel.setText("Hospitalization");

        ReasonForHospitalizationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReasonForHospitalizationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReasonForHospitalizationLabel.setText("Reason for hospitalization");

        DateOfEntryLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DateOfEntryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateOfEntryLabel.setText("Date of entry");

        DateOfEntryTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        EstimatedDurationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EstimatedDurationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstimatedDurationLabel.setText("Estimated duration");

        EstimatedDurationTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        Hospitalization_ObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Hospitalization_ObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hospitalization_ObservationsLabel.setText("Observations");

        Hospitalization_ObservationsTextArea.setColumns(20);
        Hospitalization_ObservationsTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Hospitalization_ObservationsTextArea.setRows(5);
        Hospitalization_ObservationsScrollPane.setViewportView(Hospitalization_ObservationsTextArea);

        GenerateButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenerateButton.setText("Generate");
        GenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateButtonActionPerformed(evt);
            }
        });

        RequestsComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        RequestsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestsRadioButton.setText("Requests");

        PatientIDRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientIDRadioButton.setText("Patient ID");

        DiagnosisTextArea.setColumns(20);
        DiagnosisTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DiagnosisTextArea.setRows(5);
        DiagnosisScrollPane.setViewportView(DiagnosisTextArea);

        ObservationsTextArea.setColumns(20);
        ObservationsTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ObservationsTextArea.setRows(5);
        ObservationsScrollPane.setViewportView(ObservationsTextArea);

        RecommendedTreatmentTextArea.setColumns(20);
        RecommendedTreatmentTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RecommendedTreatmentTextArea.setRows(5);
        RecommendedTreatmentScrollPane.setViewportView(RecommendedTreatmentTextArea);

        FollowUpIndicationTextArea.setColumns(20);
        FollowUpIndicationTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FollowUpIndicationTextArea.setRows(5);
        FollowUpIndicationScrollPane.setViewportView(FollowUpIndicationTextArea);

        Separator_Complete_.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CancelButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        RequestAppointment_PatientIDComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestAppointment_PatientIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        ReasonForHospitalizationTextArea.setColumns(20);
        ReasonForHospitalizationTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReasonForHospitalizationTextArea.setRows(5);
        ReasonForHospitalizationScrollPane.setViewportView(ReasonForHospitalizationTextArea);

        javax.swing.GroupLayout RequestAppointmentsPanelLayout = new javax.swing.GroupLayout(RequestAppointmentsPanel);
        RequestAppointmentsPanel.setLayout(RequestAppointmentsPanelLayout);
        RequestAppointmentsPanelLayout.setHorizontalGroup(
            RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                                        .addComponent(AcceptAppointment_AcceptButton)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                                        .addComponent(AppointmentIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(AppointmentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Separator_Accept_Reschedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AcceptMedicalAppointmentLabel)
                        .addGap(22, 22, 22)))
                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RescheduleMedicalAppointmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Reschedule_AppointmentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NewTimeAppointmentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ReasonForAppointmentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                            .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(Reschedule_AppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(NewTimeAppointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(ReasonAppointmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(RescheduleAppointment_AcceptButton)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator_Reschedule_Complete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(CompleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Complete_AppointmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CompleteMedicalAppointmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(Complete_AppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DiagnosisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Complete_ObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FollowUpIndicationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RecommendTreatmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(DiagnosisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(ObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(RecommendedTreatmentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(FollowUpIndicationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(Separator_Complete_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HospitalizationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DateOfEntryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EstimatedDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Hospitalization_ObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateOfEntryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EstimatedDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addComponent(CancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GenerateButton))
                            .addComponent(Hospitalization_ObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RequestsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(RequestsRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addComponent(PatientIDRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addComponent(RequestAppointment_PatientIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReasonForHospitalizationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReasonForHospitalizationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        RequestAppointmentsPanelLayout.setVerticalGroup(
            RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator_Accept_Reschedule)
            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separator_Reschedule_Complete)
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CompleteMedicalAppointmentLabel)
                        .addGap(10, 10, 10)
                        .addComponent(Complete_AppointmentLabel)
                        .addGap(18, 18, 18)
                        .addComponent(Complete_AppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DiagnosisLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DiagnosisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Complete_ObservationsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RecommendTreatmentLabel)
                        .addGap(18, 18, 18)
                        .addComponent(RecommendedTreatmentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FollowUpIndicationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FollowUpIndicationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CompleteButton)
                        .addGap(12, 12, 12))
                    .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                        .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(AcceptMedicalAppointmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentIDLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(AcceptAppointment_AcceptButton))
                            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(RescheduleMedicalAppointmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Reschedule_AppointmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Reschedule_AppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NewTimeAppointmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(NewTimeAppointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ReasonForAppointmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ReasonAppointmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(RescheduleAppointment_AcceptButton)))
                        .addGap(18, 18, Short.MAX_VALUE))))
            .addGroup(RequestAppointmentsPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(HospitalizationLabel)
                .addGap(18, 18, 18)
                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RequestsRadioButton)
                    .addComponent(PatientIDRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RequestsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RequestAppointment_PatientIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ReasonForHospitalizationLabel)
                .addGap(16, 16, 16)
                .addComponent(ReasonForHospitalizationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateOfEntryLabel)
                .addGap(18, 18, 18)
                .addComponent(DateOfEntryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EstimatedDurationLabel)
                .addGap(18, 18, 18)
                .addComponent(EstimatedDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Hospitalization_ObservationsLabel)
                .addGap(18, 18, 18)
                .addComponent(Hospitalization_ObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RequestAppointmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateButton)
                    .addComponent(CancelButton))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Separator_Complete_, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        DoctorViewTabbedPane.addTab("Request/Appointments", RequestAppointmentsPanel);

        PrescribeMedication_AppointmentIDLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PrescribeMedication_AppointmentIDLabel.setText("Appointment ID");

        MedicationNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        MedicationNameLabel.setText("Medication name");

        MedicationNameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        MedicationNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicationNameTextFieldActionPerformed(evt);
            }
        });

        DoseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DoseLabel.setText("Dose");

        DoseTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AdministrationRouteLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AdministrationRouteLabel.setText("Administration route");

        AdministrationRouteTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        FrecuencyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FrecuencyLabel.setText("Frecuency");

        FrecuencyTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        TreatmentDurationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        TreatmentDurationLabel.setText("Treatment duration");

        TreatmentDurationTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AdditionalInstructionsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AdditionalInstructionsLabel.setText("Additional instructions");

        AdditionalInstructionsTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PrescribeMedicationsScrollPane.setViewportView(jTable1);

        AddButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        PrescribeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PrescribeButton.setText("Prescribe");
        PrescribeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrescribeButtonActionPerformed(evt);
            }
        });

        PrescribeMedication_AppointmentIDComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PrescribeMedication_AppointmentIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout PrescribeMedicationsPanelLayout = new javax.swing.GroupLayout(PrescribeMedicationsPanel);
        PrescribeMedicationsPanel.setLayout(PrescribeMedicationsPanelLayout);
        PrescribeMedicationsPanelLayout.setHorizontalGroup(
            PrescribeMedicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                .addGroup(PrescribeMedicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(PrescribeMedicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrescribeMedicationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                                .addGroup(PrescribeMedicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                                        .addComponent(PrescribeMedication_AppointmentIDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PrescribeMedication_AppointmentIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(MedicationNameLabel))
                                    .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                                        .addComponent(TreatmentDurationLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TreatmentDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PrescribeMedicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                                        .addComponent(AdditionalInstructionsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AdditionalInstructionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FrecuencyLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FrecuencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                                        .addComponent(MedicationNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(DoseLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AdministrationRouteLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AdministrationRouteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddButton))))
                    .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(PrescribeButton)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        PrescribeMedicationsPanelLayout.setVerticalGroup(
            PrescribeMedicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrescribeMedicationsPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(PrescribeMedicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrescribeMedication_AppointmentIDLabel)
                    .addComponent(MedicationNameLabel)
                    .addComponent(MedicationNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoseLabel)
                    .addComponent(DoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdministrationRouteLabel)
                    .addComponent(AdministrationRouteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton)
                    .addComponent(PrescribeMedication_AppointmentIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PrescribeMedicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TreatmentDurationLabel)
                    .addComponent(TreatmentDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdditionalInstructionsLabel)
                    .addComponent(AdditionalInstructionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrecuencyLabel)
                    .addComponent(FrecuencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(PrescribeMedicationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(PrescribeButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        DoctorViewTabbedPane.addTab("Prescribe medications", PrescribeMedicationsPanel);

        javax.swing.GroupLayout LayoutPanelRoundLayout = new javax.swing.GroupLayout(LayoutPanelRound);
        LayoutPanelRound.setLayout(LayoutPanelRoundLayout);
        LayoutPanelRoundLayout.setHorizontalGroup(
            LayoutPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutPanelRoundLayout.createSequentialGroup()
                .addGroup(LayoutPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SuperiorPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DoctorViewTabbedPane))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LayoutPanelRoundLayout.setVerticalGroup(
            LayoutPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutPanelRoundLayout.createSequentialGroup()
                .addComponent(SuperiorPanelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorViewTabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SuperiorPanelRoundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorPanelRoundMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_SuperiorPanelRoundMousePressed

    private void SuperiorPanelRoundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorPanelRoundMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_SuperiorPanelRoundMouseDragged

    private void ExitButtonDoctorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonDoctorViewActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonDoctorViewActionPerformed

    private void PendingAppointmentsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingAppointmentsRadioButtonActionPerformed
        // TODO add your handling code here:
        TotalAppointmentsRadioButton.setSelected(false);
        Doctor d = doctor;
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        for (Appointment a : d.getAppointments()) {
            if (a.getStatus().equals(AppointmentStatus.PENDING)) {
                model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getPatient().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In person" : "Virtual", a.getStatus().name()});
            }
        }
    }//GEN-LAST:event_PendingAppointmentsRadioButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        String firstname = FirstnameTextField.getText();
        String lastname = LastnameTextField.getText();
        String spec = SpecialtyComboBox.getItemAt(SpecialtyComboBox.getSelectedIndex());
        String licenseNumber = LicenseNumberTextField.getText();
        String assignedOffice = AssignedOfficeTextField.getText();
        String username = UserTextField.getText();
        String password = PasswordTextField.getText();
        String comPassword = PasswordConfirmTextField.getText();
        Specialty specialty = Specialty.valueOf(spec.replaceAll(" &", "").replaceAll(" ", "_"));
        if (password.equals(comPassword)) {
            for(User doc: this.users){
                if (doctor.getId() == doc.getId()) {
                    doctor.setFirstname(firstname);
                    doctor.setLastname(lastname);
                    doctor.setPassword(password);
                    doctor.setUsername(username);
                    doctor.setAssignedOffice(assignedOffice);
                    doctor.setLicenceNumber(licenseNumber);
                    doctor.setSpecialty(specialty);
                    
                }
            }
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.setVisible(false);
        new LoginView(createLoginController()).setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        AdminView admin = new AdminView(user,users,hospitalizations, appointments);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        if (RequestsRadioButton.isSelected()) {
            for(Hospitalization hosp : this.hospitalizations){
                if (RequestsComboBox.getItemAt(RequestsComboBox.getSelectedIndex()) == hosp.getId()) {
                    hosp.setStatus(HospitalizationStatus.CANCELED);
                }
            }
        }
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void GenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateButtonActionPerformed
        if (PatientIDRadioButton.isSelected()) {
            for(User user: this.users){
                if (user instanceof Patient) {
                    if (RequestAppointment_PatientIDComboBox.getItemAt(RequestAppointment_PatientIDComboBox.getSelectedIndex()).equals(user.getId())) {
                        if (this.user instanceof Administrator) {
                            String reason = ReasonForHospitalizationTextArea.getText();
                            String observations = Hospitalization_ObservationsTextArea.getText();
                            String entDate = DateOfEntryTextField.getText();
                            LocalDate entryDate = LocalDate.of(Integer.parseInt(entDate.substring(0, 4)), Integer.parseInt(entDate.substring(5, 7)), Integer.parseInt(entDate.substring(8)));
                            this.hospitalizations.add(new Hospitalization("asdfasdf", (Patient)user, this.doctor, LocalDate.MAX, reason, RoomType.IMC, observations, HospitalizationStatus.ONGOING));
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_GenerateButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        Patient p = null;
        for (User u : this.users) {
            if (u.getId() == Long.parseLong(PatientComboBox.getItemAt(PatientComboBox.getSelectedIndex()))) {
                p = (Patient) u;
            }
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        for (Appointment a : p.getAppointments()) {
            model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getDoctor().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In-person" : "Remote", a.getStatus().name()});
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void TotalAppointmentsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalAppointmentsRadioButtonActionPerformed
        // TODO add your handling code here:
        PendingAppointmentsRadioButton.setSelected(false);
        Doctor d = doctor;
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        for (Appointment a : d.getAppointments()) {
            model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getPatient().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In-person" : "Remote", a.getStatus().name()});
        }
    }//GEN-LAST:event_TotalAppointmentsRadioButtonActionPerformed

    private void AcceptAppointment_AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptAppointment_AcceptButtonActionPerformed
        String idAppointment = AppointmentIDComboBox.getItemAt(AppointmentIDComboBox.getSelectedIndex());
        for(Appointment apo: this.appointments){
            if(apo.getId() == idAppointment){
                apo.setStatus(AppointmentStatus.PENDING);
            }
        }
    }//GEN-LAST:event_AcceptAppointment_AcceptButtonActionPerformed

    private void CompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteButtonActionPerformed
        String idAppointment = Complete_AppointmentComboBox.getItemAt(Complete_AppointmentComboBox.getSelectedIndex());
        String diagnosis = DiagnosisTextArea.getText();
        String observations = ObservationsTextArea.getText();
        String recommendedTrea = RecommendedTreatmentTextArea.getText();
        String followUp = FollowUpIndicationTextArea.getText();
        for(Appointment apo: this.appointments){
            if(apo.getId() == idAppointment){
                apo.setStatus(AppointmentStatus.CANCELED);
                apo.setDiagnosis(diagnosis);
                apo.setFollowUp(followUp);
                apo.setRecommendedTreatment(recommendedTrea);
                apo.setObservations(observations);
            }
        }
    }//GEN-LAST:event_CompleteButtonActionPerformed

    private void PrescribeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrescribeButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_PrescribeButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        String appointmentId = PrescribeMedication_AppointmentIDComboBox.getItemAt(PrescribeMedication_AppointmentIDComboBox.getSelectedIndex());
        String medicationName = MedicationNameTextField.getText();
        double dose = Double.parseDouble(DoseTextField.getText());
        String administrationRoute = AdministrationRouteTextField.getText();
        int tratementduration = Integer.parseInt(TreatmentDurationTextField.getText());
        String aditionalIformation = AdditionalInstructionsTextField.getText();
        int frecuency = Integer.parseInt(FrecuencyTextField.getText());
        
        model.addRow(new Object[]{appointmentId, medicationName, DoseTextField.getText(), administrationRoute, "" + tratementduration, aditionalIformation, "" + frecuency});
        for(Appointment apo: this.appointments){
            if (apo.getId().equals(appointmentId)){
                apo.addPrescription(new Prescription(apo, medicationName, dose, administrationRoute, tratementduration, aditionalIformation, frecuency));
            }
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void RescheduleAppointment_AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RescheduleAppointment_AcceptButtonActionPerformed
        String appointmentId = Reschedule_AppointmentComboBox.getItemAt(Reschedule_AppointmentComboBox.getSelectedIndex());
        Appointment appointment = null;
        for(Appointment apo: this.appointments){
            if (apo.getId().equals(appointmentId)) {
                appointment = apo;
            }
        }
        appointment.getDatetime().with(LocalTime.of(Integer.parseInt(NewTimeAppointTextField.getText().substring(0, 2)),Integer.parseInt(NewTimeAppointTextField.getText().substring(3))));
        String reasonChangeTime = ReasonAppointmentTextField.getText();
        appointment.setReason(reasonChangeTime);
    }//GEN-LAST:event_RescheduleAppointment_AcceptButtonActionPerformed

    private void MedicationNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicationNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicationNameTextFieldActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptAppointment_AcceptButton;
    private javax.swing.JLabel AcceptMedicalAppointmentLabel;
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AdditionalInstructionsLabel;
    private javax.swing.JTextField AdditionalInstructionsTextField;
    private javax.swing.JLabel AdministrationRouteLabel;
    private javax.swing.JTextField AdministrationRouteTextField;
    private javax.swing.JComboBox<String> AppointmentIDComboBox;
    private javax.swing.JLabel AppointmentIDLabel;
    private javax.swing.JPanel AppointmentsVisualizationPanel;
    private javax.swing.JScrollPane AppointmentsVisualizationScrollPane;
    private javax.swing.JLabel AssignedOfficeLabel;
    private javax.swing.JTextField AssignedOfficeTextField;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CompleteButton;
    private javax.swing.JLabel CompleteMedicalAppointmentLabel;
    private javax.swing.JComboBox<String> Complete_AppointmentComboBox;
    private javax.swing.JLabel Complete_AppointmentLabel;
    private javax.swing.JLabel Complete_ObservationsLabel;
    private javax.swing.JLabel DateOfEntryLabel;
    private javax.swing.JTextField DateOfEntryTextField;
    private javax.swing.JLabel DiagnosisLabel;
    private javax.swing.JScrollPane DiagnosisScrollPane;
    private javax.swing.JTextArea DiagnosisTextArea;
    private javax.swing.JLabel DoctorViewLabel;
    private javax.swing.JTabbedPane DoctorViewTabbedPane;
    private javax.swing.JLabel DoseLabel;
    private javax.swing.JTextField DoseTextField;
    private javax.swing.JLabel EstimatedDurationLabel;
    private javax.swing.JTextField EstimatedDurationTextField;
    private javax.swing.JButton ExitButtonDoctorView;
    private javax.swing.JLabel FirstnameLabel;
    private javax.swing.JTextField FirstnameTextField;
    private javax.swing.JLabel FollowUpIndicationLabel;
    private javax.swing.JScrollPane FollowUpIndicationScrollPane;
    private javax.swing.JTextArea FollowUpIndicationTextArea;
    private javax.swing.JLabel FrecuencyLabel;
    private javax.swing.JTextField FrecuencyTextField;
    private javax.swing.JButton GenerateButton;
    private javax.swing.JPanel HistoryAppointmentsPatientPanel;
    private javax.swing.JScrollPane HistoryAppointmentsPatientScrollPane;
    private javax.swing.JLabel HospitalizationLabel;
    private javax.swing.JLabel Hospitalization_ObservationsLabel;
    private javax.swing.JScrollPane Hospitalization_ObservationsScrollPane;
    private javax.swing.JTextArea Hospitalization_ObservationsTextArea;
    private javax.swing.JLabel LastnameLabel;
    private javax.swing.JTextField LastnameTextField;
    private packagee.PanelRound LayoutPanelRound;
    private javax.swing.JLabel LicenseNumberLabel;
    private javax.swing.JTextField LicenseNumberTextField;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel MedicationNameLabel;
    private javax.swing.JTextField MedicationNameTextField;
    private javax.swing.JPanel ModifyInfoPanel;
    private javax.swing.JTextField NewTimeAppointTextField;
    private javax.swing.JLabel NewTimeAppointmentLabel;
    private javax.swing.JScrollPane ObservationsScrollPane;
    private javax.swing.JTextArea ObservationsTextArea;
    private javax.swing.JLabel PasswordConfirmLabel;
    private javax.swing.JTextField PasswordConfirmTextField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JComboBox<String> PatientComboBox;
    private javax.swing.JRadioButton PatientIDRadioButton;
    private javax.swing.JLabel PatientLabel;
    private javax.swing.JRadioButton PendingAppointmentsRadioButton;
    private javax.swing.JButton PrescribeButton;
    private javax.swing.JComboBox<String> PrescribeMedication_AppointmentIDComboBox;
    private javax.swing.JLabel PrescribeMedication_AppointmentIDLabel;
    private javax.swing.JPanel PrescribeMedicationsPanel;
    private javax.swing.JScrollPane PrescribeMedicationsScrollPane;
    private javax.swing.JTextField ReasonAppointmentTextField;
    private javax.swing.JLabel ReasonForAppointmentLabel;
    private javax.swing.JLabel ReasonForHospitalizationLabel;
    private javax.swing.JScrollPane ReasonForHospitalizationScrollPane;
    private javax.swing.JTextArea ReasonForHospitalizationTextArea;
    private javax.swing.JLabel RecommendTreatmentLabel;
    private javax.swing.JScrollPane RecommendedTreatmentScrollPane;
    private javax.swing.JTextArea RecommendedTreatmentTextArea;
    private javax.swing.JComboBox<String> RequestAppointment_PatientIDComboBox;
    private javax.swing.JPanel RequestAppointmentsPanel;
    private javax.swing.JComboBox<String> RequestsComboBox;
    private javax.swing.JRadioButton RequestsRadioButton;
    private javax.swing.JButton RescheduleAppointment_AcceptButton;
    private javax.swing.JLabel RescheduleMedicalAppointmentLabel;
    private javax.swing.JComboBox<String> Reschedule_AppointmentComboBox;
    private javax.swing.JLabel Reschedule_AppointmentLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JSeparator Separator_Accept_Reschedule;
    private javax.swing.JSeparator Separator_Complete_;
    private javax.swing.JSeparator Separator_Reschedule_Complete;
    private javax.swing.JComboBox<String> SpecialtyComboBox;
    private javax.swing.JLabel SpecialtyLabel;
    private packagee.PanelRound SuperiorPanelRound;
    private javax.swing.JRadioButton TotalAppointmentsRadioButton;
    private javax.swing.JLabel TreatmentDurationLabel;
    private javax.swing.JTextField TreatmentDurationTextField;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
