/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Administrator;
import modelo.Appointment;
import modelo.Doctor;
import modelo.Hospitalization;
import modelo.Patient;
import modelo.User;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LoginView extends javax.swing.JFrame {

    private int x, y;
    private LoginController loginController;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;

    public LoginView(LoginController loginController) {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        
        this.loginController = loginController;
        this.users = loginController.getUsers();
        this.appointments = loginController.getAppointments();
        this.hospitalizations = loginController.getHospitalizations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutPanelRound = new packagee.PanelRound();
        SuperiorPanelRound = new packagee.PanelRound();
        ExitButton = new javax.swing.JButton();
        MenuTabbedPane = new javax.swing.JTabbedPane();
        LowerPanelRound = new packagee.PanelRound();
        LoginLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        EnterButton = new javax.swing.JButton();
        PatientRegisterPanel = new javax.swing.JPanel();
        FirstnameLabel = new javax.swing.JLabel();
        FirstnameTextField = new javax.swing.JTextField();
        LastnameLabel = new javax.swing.JLabel();
        LastnameTextField = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        UserTextField = new javax.swing.JTextField();
        PatientRegister_PasswordTextField = new javax.swing.JTextField();
        PatientRegister_PasswordLabel = new javax.swing.JLabel();
        PatientRegister_PasswordConfirmLabel = new javax.swing.JLabel();
        PatientRegister_PasswordConfirmTextField = new javax.swing.JTextField();
        GenderComboBox = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        AdressLabel = new javax.swing.JLabel();
        AdressTextField = new javax.swing.JTextField();
        BirthdateLabel = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LayoutPanelRound.setRadius(50);

        SuperiorPanelRound.setRadius(50);
        SuperiorPanelRound.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SuperiorPanelRoundMouseDragged(evt);
            }
        });
        SuperiorPanelRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SuperiorPanelRoundMousePressed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ExitButton.setText("X");
        ExitButton.setBorderPainted(false);
        ExitButton.setContentAreaFilled(false);
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitButton.setFocusable(false);
        ExitButton.setRequestFocusEnabled(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuperiorPanelRoundLayout = new javax.swing.GroupLayout(SuperiorPanelRound);
        SuperiorPanelRound.setLayout(SuperiorPanelRoundLayout);
        SuperiorPanelRoundLayout.setHorizontalGroup(
            SuperiorPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorPanelRoundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addGap(19, 19, 19))
        );
        SuperiorPanelRoundLayout.setVerticalGroup(
            SuperiorPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LoginLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LoginLabel.setText("LOGIN");

        UsernameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UsernameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        UsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UsernameLabel.setText("USERNAME");

        PasswordTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswordTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswordLabel.setText("PASSWORD");

        EnterButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EnterButton.setText("ENTER");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LowerPanelRoundLayout = new javax.swing.GroupLayout(LowerPanelRound);
        LowerPanelRound.setLayout(LowerPanelRoundLayout);
        LowerPanelRoundLayout.setHorizontalGroup(
            LowerPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LowerPanelRoundLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(LoginLabel)
                .addGap(481, 481, 481))
            .addGroup(LowerPanelRoundLayout.createSequentialGroup()
                .addGroup(LowerPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LowerPanelRoundLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(LowerPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LowerPanelRoundLayout.createSequentialGroup()
                                .addGroup(LowerPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LowerPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LowerPanelRoundLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(EnterButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LowerPanelRoundLayout.setVerticalGroup(
            LowerPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerPanelRoundLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(LoginLabel)
                .addGap(74, 74, 74)
                .addComponent(UsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(EnterButton)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        MenuTabbedPane.addTab("Login", LowerPanelRound);

        FirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FirstnameLabel.setText("Firstname");

        FirstnameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        LastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LastnameLabel.setText("Lastname");

        LastnameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        IDLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        IDLabel.setText("ID");

        IDTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        GenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenderLabel.setText("Gender");

        PhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PhoneLabel.setText("Phone");

        PhoneTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        EmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        EmailTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        UserLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserLabel.setText("User");

        UserTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PatientRegister_PasswordTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PatientRegister_PasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientRegister_PasswordLabel.setText("Password");

        PatientRegister_PasswordConfirmLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientRegister_PasswordConfirmLabel.setText("Password confirmation");

        PatientRegister_PasswordConfirmTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientRegister_PasswordConfirmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientRegister_PasswordConfirmTextFieldActionPerformed(evt);
            }
        });

        GenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        Save.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        AdressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AdressLabel.setText("Address");

        AdressTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        BirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BirthdateLabel.setText("Birthdate");

        jTextField12.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout PatientRegisterPanelLayout = new javax.swing.GroupLayout(PatientRegisterPanel);
        PatientRegisterPanel.setLayout(PatientRegisterPanelLayout);
        PatientRegisterPanelLayout.setHorizontalGroup(
            PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(PatientRegister_PasswordLabel))
                    .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientRegister_PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(UserLabel))
                    .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(PatientRegister_PasswordConfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(Save))
                    .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(PatientRegister_PasswordConfirmLabel))
                    .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                                .addComponent(BirthdateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                                .addComponent(FirstnameLabel)
                                .addGap(34, 34, 34)
                                .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastnameLabel)
                            .addComponent(AdressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                                .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(IDLabel)
                                .addGap(30, 30, 30)
                                .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenderLabel)
                                .addGap(26, 26, 26)
                                .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                                .addComponent(AdressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PhoneLabel)
                                .addGap(18, 18, 18)
                                .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmailLabel)
                                .addGap(18, 18, 18)
                                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        PatientRegisterPanelLayout.setVerticalGroup(
            PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientRegisterPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstnameLabel)
                    .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastnameLabel)
                    .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLabel)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderLabel)
                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BirthdateLabel)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AdressLabel)
                        .addComponent(AdressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PhoneLabel)
                        .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmailLabel)
                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(UserLabel)
                .addGap(18, 18, 18)
                .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientRegister_PasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(PatientRegister_PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PatientRegister_PasswordConfirmLabel)
                .addGap(18, 18, 18)
                .addComponent(PatientRegister_PasswordConfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Save)
                .addGap(42, 42, 42))
        );

        MenuTabbedPane.addTab("Patient register", PatientRegisterPanel);

        javax.swing.GroupLayout LayoutPanelRoundLayout = new javax.swing.GroupLayout(LayoutPanelRound);
        LayoutPanelRound.setLayout(LayoutPanelRoundLayout);
        LayoutPanelRoundLayout.setHorizontalGroup(
            LayoutPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuperiorPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LayoutPanelRoundLayout.createSequentialGroup()
                .addComponent(MenuTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LayoutPanelRoundLayout.setVerticalGroup(
            LayoutPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutPanelRoundLayout.createSequentialGroup()
                .addComponent(SuperiorPanelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuTabbedPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SuperiorPanelRoundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorPanelRoundMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_SuperiorPanelRoundMousePressed

    private void SuperiorPanelRoundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorPanelRoundMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_SuperiorPanelRoundMouseDragged

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        // TODO add your handling code here:
        String username = UsernameTextField.getText();
        String password = PasswordTextField.getText();

        User selectedUser = null;

        for (User user : this.users) {
            if (username.equals(user.getUsername())) {
            
                selectedUser = user;
            
                if (password.equals(selectedUser.getPassword())) {
                
                    JOptionPane.showMessageDialog(this, "[✅] You have successfully logged in");
                
                    if (selectedUser instanceof Administrator) {
                        AdminView admin = new AdminView(selectedUser, users, hospitalizations, appointments);
                        this.setVisible(false);
                        admin.setVisible(true);
                    }

                    else if (selectedUser instanceof Doctor) {
                        DoctorView doctor = new DoctorView(selectedUser, (Doctor) selectedUser, users, hospitalizations, appointments);
                        this.setVisible(false);
                        doctor.setVisible(true);
                    }

                    else {
                        PatientView patient = new PatientView(selectedUser, (Patient) selectedUser, users, appointments, hospitalizations);
                        this.setVisible(false);
                        patient.setVisible(true);
                    }
                    return;
                }
            }
        }
    
        //Mensaje de error
        JOptionPane.showMessageDialog(this, "[⚠] Error: Incorrect username or password");
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String firstname = FirstnameTextField.getText();
        String lastname = LastnameTextField.getText();
        long id = Long.parseLong(IDTextField.getText());
        boolean gender = (GenderComboBox.getSelectedIndex() == 0 ? null : (GenderComboBox.getSelectedIndex() == 1 ));
        String birth = jTextField12.getText();
        String address = AdressTextField.getText();
        long phone = Long.parseLong(PhoneTextField.getText());
        String email = EmailTextField.getText();
        String user = UserTextField.getText();
        String password = PatientRegister_PasswordTextField.getText();
        String comPassword = PatientRegister_PasswordConfirmTextField.getText();
        LocalDate birthdate = LocalDate.of(Integer.parseInt(birth.substring(0, 4)), Integer.parseInt(birth.substring(5, 7)), Integer.parseInt(birth.substring(8)));
        if (comPassword.equals(password)) {
            users.add(new Patient(id, user, firstname, lastname, password, email, birthdate, gender, phone, address));
        }
        
    }//GEN-LAST:event_SaveActionPerformed

    private void PatientRegister_PasswordConfirmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientRegister_PasswordConfirmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientRegister_PasswordConfirmTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdressLabel;
    private javax.swing.JTextField AdressTextField;
    private javax.swing.JLabel BirthdateLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JButton EnterButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel FirstnameLabel;
    private javax.swing.JTextField FirstnameTextField;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel LastnameLabel;
    private javax.swing.JTextField LastnameTextField;
    private packagee.PanelRound LayoutPanelRound;
    private javax.swing.JLabel LoginLabel;
    private packagee.PanelRound LowerPanelRound;
    private javax.swing.JTabbedPane MenuTabbedPane;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JPanel PatientRegisterPanel;
    private javax.swing.JLabel PatientRegister_PasswordConfirmLabel;
    private javax.swing.JTextField PatientRegister_PasswordConfirmTextField;
    private javax.swing.JLabel PatientRegister_PasswordLabel;
    private javax.swing.JTextField PatientRegister_PasswordTextField;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton Save;
    private packagee.PanelRound SuperiorPanelRound;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JTextField jTextField12;
    // End of variables declaration//GEN-END:variables
}
