/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Administrator;
import modelo.Appointment;
import modelo.AppointmentStatus;
import modelo.Doctor;
import modelo.Hospitalization;
import modelo.Patient;
import modelo.RoomType;
import modelo.Specialty;
import modelo.User;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class PatientView extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private Patient patient;
    private ArrayList<Appointment> appointments;
    private ArrayList<Hospitalization> hospitalizations;
    private PatientController patientController;
    private HospitalizationController hospitalizationController;

    public PatientView(User user, Patient patient, ArrayList<User> users, ArrayList<Appointment>appointments, ArrayList<Hospitalization> hospitalizations) {
        initComponents();
        this.user = user;
        this.users = users;
        this.patient = patient;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        this.patientController = new PatientController(users, appointments, hospitalizations);
        hospitalizationController = new HospitalizationController();
        
        loadDoctors();
        loadRoomTypes();
        loadAppointmentsToCancel();
        loadAppointmentHistory();
        loadPatientData();
        
        if (user instanceof Administrator) {
            BackButton.setVisible(true);
        } else {
            BackButton.setVisible(false);
        }
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }
    
    private LoginController createLoginController() {
        LoginController loginController = new LoginController(patientController.getUsers(), patientController.getAppointments(), patientController.getHospitalizations());
        return loginController;
    }
    
    private void clearSaveForm() {
        UserTextField.setText("");
        FirstnameTextField.setText("");
        LastnameTextField.setText("");
        PasswordTextField.setText("");
        PasswordConfirmTextField.setText("");
        EmailTextField.setText("");
        BirthdateTextField.setText("");
        PhoneTextField.setText("");
        AdressTextField.setText("");
        GenderComboBox.setSelectedIndex(0);
    }
    
    private void loadDoctors() {
        AttendingDoctorComboBox.removeAllItems();
        AttendingDoctorComboBox.addItem("Select one");

        for (String doctor : patientController.getDoctors()) {
            AttendingDoctorComboBox.addItem(doctor);
        }
    }

    private void loadRoomTypes() {
        DesiredRoomTypeComboBox.removeAllItems();
        
        for (RoomType room : RoomType.values()) {
            DesiredRoomTypeComboBox.addItem(room.toString());
        }
    }

    private void loadAppointmentsToCancel() {
        IDAppointmentComboBox.removeAllItems();
        IDAppointmentComboBox.addItem("Select one");
        
        for (Appointment appointment : appointments) {
            if (appointment.getPatient().equals(patient)) {
                if (appointment.getStatus() != AppointmentStatus.CANCELED) {
                    IDAppointmentComboBox.addItem(appointment.getId());
                }
            }
        }
    }

    private void loadAppointmentHistory() {
        DefaultTableModel model =(DefaultTableModel) AppointmentHistory_Table.getModel();
        model.setRowCount(0);
        for (Object[] row : patientController.getPatientAppointments(patient)) {
            model.addRow(row);
        }
    }

    private void loadPatientData() {
        UserTextField.setText(patient.getUsername());
        FirstnameTextField.setText(patient.getFirstname());
        LastnameTextField.setText(patient.getLastname());
        EmailTextField.setText(patient.getEmail());
        PhoneTextField.setText(String.valueOf(patient.getPhone()));
        AdressTextField.setText(patient.getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayoutPanelRound = new packagee.PanelRound();
        SuperiorPanelRound = new packagee.PanelRound();
        ExitButtonPatientView = new javax.swing.JButton();
        PatientViewLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        PatientViewTabbedPane = new javax.swing.JTabbedPane();
        AppointmentHistoryPanel = new javax.swing.JPanel();
        AppointmentHistory_ScrollPane = new javax.swing.JScrollPane();
        AppointmentHistory_Table = new javax.swing.JTable();
        RefreshButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        ModifyInfoPanel = new javax.swing.JPanel();
        FirstnameLabel = new javax.swing.JLabel();
        FirstnameTextField = new javax.swing.JTextField();
        LastnameLabel = new javax.swing.JLabel();
        LastnameTextField = new javax.swing.JTextField();
        BirthdateLabel = new javax.swing.JLabel();
        BirthdateTextField = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        AdressLabel = new javax.swing.JLabel();
        AdressTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordConfirmLabel = new javax.swing.JLabel();
        PasswordConfirmTextField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        UserLabel = new javax.swing.JLabel();
        UserTextField = new javax.swing.JTextField();
        GenderComboBox = new javax.swing.JComboBox<>();
        RequestCancelPanel = new javax.swing.JPanel();
        RequestMedicalAppointmentLabel = new javax.swing.JLabel();
        SpecialtyRadioButton = new javax.swing.JRadioButton();
        DoctorRadioButton = new javax.swing.JRadioButton();
        Separator_MedicalAppointment_Hospitalization = new javax.swing.JSeparator();
        AppointmentDateLabel = new javax.swing.JLabel();
        AppointmentDateTextField = new javax.swing.JTextField();
        AppointmentTimeTextField = new javax.swing.JTextField();
        AppointmentTimeLabel = new javax.swing.JLabel();
        AppointmentTypeLabel = new javax.swing.JLabel();
        AppointmentReasonLabel = new javax.swing.JLabel();
        AppointmentTypeComboBox = new javax.swing.JComboBox<>();
        CreateMedicalAppointmentButton = new javax.swing.JButton();
        Separator_Hospitalization_Cancel = new javax.swing.JSeparator();
        RequestHospitalizationLab = new javax.swing.JLabel();
        HospitalizationReasonLabel = new javax.swing.JLabel();
        AttendingDoctorLabel = new javax.swing.JLabel();
        AttendingDoctorComboBox = new javax.swing.JComboBox<>();
        EstimatedDateAdmissionTextField = new javax.swing.JTextField();
        EstimatedDateAdmissionLabel = new javax.swing.JLabel();
        DesiredRoomTypeLabel = new javax.swing.JLabel();
        DesiredRoomTypeComboBox = new javax.swing.JComboBox<>();
        HospitalizationObservationsLabel = new javax.swing.JLabel();
        Hospitalization_ObservationsScrollPane = new javax.swing.JScrollPane();
        Hospitalization_ObservationsTextArea = new javax.swing.JTextArea();
        CreateHospitalizationButton = new javax.swing.JButton();
        CancelAppointmentLabel = new javax.swing.JLabel();
        IDAppointmentLabel = new javax.swing.JLabel();
        CancelAppointmentObservationLabel = new javax.swing.JLabel();
        Cancel_ObservationsScrollPane = new javax.swing.JScrollPane();
        Cancel_ObservationsTextArea = new javax.swing.JTextArea();
        CancelButton = new javax.swing.JButton();
        HospitalizationReasonScrollPane = new javax.swing.JScrollPane();
        HospitalizationReasonTextArea = new javax.swing.JTextArea();
        AppointmentReasonScrollPane = new javax.swing.JScrollPane();
        AppointmentReasonTextArea = new javax.swing.JTextArea();
        IDAppointmentComboBox = new javax.swing.JComboBox<>();
        RequestMedicalAppointmentComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LayoutPanelRound.setRadius(50);

        SuperiorPanelRound.setRadius(50);
        SuperiorPanelRound.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SuperiorPanelRoundMouseDragged(evt);
            }
        });
        SuperiorPanelRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SuperiorPanelRoundMousePressed(evt);
            }
        });

        ExitButtonPatientView.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ExitButtonPatientView.setText("X");
        ExitButtonPatientView.setBorderPainted(false);
        ExitButtonPatientView.setContentAreaFilled(false);
        ExitButtonPatientView.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitButtonPatientView.setFocusable(false);
        ExitButtonPatientView.setRequestFocusEnabled(false);
        ExitButtonPatientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonPatientViewActionPerformed(evt);
            }
        });

        PatientViewLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        PatientViewLabel.setText("PATIENT VIEW");

        BackButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuperiorPanelRoundLayout = new javax.swing.GroupLayout(SuperiorPanelRound);
        SuperiorPanelRound.setLayout(SuperiorPanelRoundLayout);
        SuperiorPanelRoundLayout.setHorizontalGroup(
            SuperiorPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorPanelRoundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PatientViewLabel)
                .addGap(29, 29, 29)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButtonPatientView)
                .addGap(19, 19, 19))
        );
        SuperiorPanelRoundLayout.setVerticalGroup(
            SuperiorPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorPanelRoundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExitButtonPatientView))
            .addGroup(SuperiorPanelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PatientViewLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AppointmentHistory_Table.setAutoCreateRowSorter(true);
        AppointmentHistory_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AppointmentHistory_ScrollPane.setViewportView(AppointmentHistory_Table);

        RefreshButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AppointmentHistoryPanelLayout = new javax.swing.GroupLayout(AppointmentHistoryPanel);
        AppointmentHistoryPanel.setLayout(AppointmentHistoryPanelLayout);
        AppointmentHistoryPanelLayout.setHorizontalGroup(
            AppointmentHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentHistoryPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(AppointmentHistory_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(AppointmentHistoryPanelLayout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(RefreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(78, 78, 78))
        );
        AppointmentHistoryPanelLayout.setVerticalGroup(
            AppointmentHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentHistoryPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AppointmentHistory_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(AppointmentHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefreshButton)
                    .addComponent(LogoutButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        PatientViewTabbedPane.addTab("Appointment history", AppointmentHistoryPanel);

        FirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FirstnameLabel.setText("Firstname");

        FirstnameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        LastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LastnameLabel.setText("Lastname");

        LastnameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        BirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BirthdateLabel.setText("Birthdate");

        BirthdateTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        GenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenderLabel.setText("Gender");

        EmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        EmailTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PhoneLabel.setText("Phone");

        PhoneTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AdressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AdressLabel.setText("Address");

        AdressTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswordTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswordLabel.setText("Password");

        PasswordConfirmLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswordConfirmLabel.setText("Password confirmation");

        PasswordConfirmTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SaveButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        UserLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserLabel.setText("User");

        UserTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        GenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout ModifyInfoPanelLayout = new javax.swing.GroupLayout(ModifyInfoPanel);
        ModifyInfoPanel.setLayout(ModifyInfoPanelLayout);
        ModifyInfoPanelLayout.setHorizontalGroup(
            ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(FirstnameLabel)
                .addGap(18, 18, 18)
                .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LastnameLabel)
                .addGap(18, 18, 18)
                .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addComponent(PhoneLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AdressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AdressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BirthdateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(BirthdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GenderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(EmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(SaveButton))
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(PasswordConfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PasswordConfirmLabel)
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(PasswordLabel))
                    .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(UserLabel)))
                            .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModifyInfoPanelLayout.setVerticalGroup(
            ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyInfoPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstnameLabel)
                    .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastnameLabel)
                    .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthdateLabel)
                    .addComponent(BirthdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderLabel)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdressLabel)
                    .addComponent(AdressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(UserLabel)
                .addGap(18, 18, 18)
                .addComponent(UserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordConfirmLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswordConfirmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(SaveButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        PatientViewTabbedPane.addTab("Modify info", ModifyInfoPanel);

        RequestMedicalAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestMedicalAppointmentLabel.setText("Request medical appointment");

        SpecialtyRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SpecialtyRadioButton.setText("Specialty");
        SpecialtyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialtyRadioButtonActionPerformed(evt);
            }
        });

        DoctorRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DoctorRadioButton.setText("Doctor");
        DoctorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorRadioButtonActionPerformed(evt);
            }
        });

        Separator_MedicalAppointment_Hospitalization.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AppointmentDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentDateLabel.setText("Appointment date");

        AppointmentDateTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AppointmentTimeTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AppointmentTimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentTimeLabel.setText("Appointment time");

        AppointmentTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentTypeLabel.setText("Appointment type");

        AppointmentReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentReasonLabel.setText("Appointment reason");

        AppointmentTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));
        AppointmentTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentTypeComboBoxActionPerformed(evt);
            }
        });

        CreateMedicalAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CreateMedicalAppointmentButton.setText("Create");
        CreateMedicalAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMedicalAppointmentButtonActionPerformed(evt);
            }
        });

        Separator_Hospitalization_Cancel.setOrientation(javax.swing.SwingConstants.VERTICAL);

        RequestHospitalizationLab.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestHospitalizationLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RequestHospitalizationLab.setText("Request hospitalization");

        HospitalizationReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospitalizationReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospitalizationReasonLabel.setText("Hospitalization reason");

        AttendingDoctorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AttendingDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AttendingDoctorLabel.setText("Attending doctor");

        AttendingDoctorComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AttendingDoctorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        EstimatedDateAdmissionTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        EstimatedDateAdmissionLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EstimatedDateAdmissionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstimatedDateAdmissionLabel.setText("Estimated date of admission");
        EstimatedDateAdmissionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DesiredRoomTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DesiredRoomTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesiredRoomTypeLabel.setText("Desired room type");

        DesiredRoomTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DesiredRoomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        HospitalizationObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospitalizationObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospitalizationObservationsLabel.setText("Observations");

        Hospitalization_ObservationsTextArea.setColumns(20);
        Hospitalization_ObservationsTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Hospitalization_ObservationsTextArea.setRows(5);
        Hospitalization_ObservationsScrollPane.setViewportView(Hospitalization_ObservationsTextArea);

        CreateHospitalizationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CreateHospitalizationButton.setText("Create");
        CreateHospitalizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateHospitalizationButtonActionPerformed(evt);
            }
        });

        CancelAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CancelAppointmentLabel.setText("Cancel appointment");

        IDAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        IDAppointmentLabel.setText("ID appointment");

        CancelAppointmentObservationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CancelAppointmentObservationLabel.setText("Observations");

        Cancel_ObservationsTextArea.setColumns(20);
        Cancel_ObservationsTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Cancel_ObservationsTextArea.setRows(5);
        Cancel_ObservationsScrollPane.setViewportView(Cancel_ObservationsTextArea);

        CancelButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        HospitalizationReasonTextArea.setColumns(20);
        HospitalizationReasonTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospitalizationReasonTextArea.setRows(5);
        HospitalizationReasonScrollPane.setViewportView(HospitalizationReasonTextArea);

        AppointmentReasonTextArea.setColumns(20);
        AppointmentReasonTextArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentReasonTextArea.setRows(5);
        AppointmentReasonScrollPane.setViewportView(AppointmentReasonTextArea);

        IDAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        IDAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        RequestMedicalAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestMedicalAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout RequestCancelPanelLayout = new javax.swing.GroupLayout(RequestCancelPanel);
        RequestCancelPanel.setLayout(RequestCancelPanelLayout);
        RequestCancelPanelLayout.setHorizontalGroup(
            RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                    .addComponent(SpecialtyRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DoctorRadioButton))
                                .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(AppointmentDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(AppointmentTimeLabel)
                                        .addComponent(AppointmentDateLabel)
                                        .addComponent(RequestMedicalAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(AppointmentTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(AppointmentReasonLabel))
                                .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(AppointmentTypeLabel))
                                .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(AppointmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(RequestMedicalAppointmentLabel)))
                    .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(AppointmentReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(CreateMedicalAppointmentButton)))
                .addGap(69, 69, 69)
                .addComponent(Separator_MedicalAppointment_Hospitalization, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(CreateHospitalizationButton))
                        .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(HospitalizationReasonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HospitalizationReasonScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(RequestHospitalizationLab, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(AttendingDoctorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestCancelPanelLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HospitalizationObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EstimatedDateAdmissionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Hospitalization_ObservationsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DesiredRoomTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(AttendingDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(EstimatedDateAdmissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(DesiredRoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(Separator_Hospitalization_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancel_ObservationsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                        .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(CancelAppointmentLabel))
                            .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(CancelButton))
                            .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IDAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDAppointmentLabel)))
                            .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(CancelAppointmentObservationLabel)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        RequestCancelPanelLayout.setVerticalGroup(
            RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator_MedicalAppointment_Hospitalization)
            .addComponent(Separator_Hospitalization_Cancel)
            .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                        .addComponent(RequestHospitalizationLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(HospitalizationReasonLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HospitalizationReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AttendingDoctorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AttendingDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EstimatedDateAdmissionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstimatedDateAdmissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(DesiredRoomTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DesiredRoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HospitalizationObservationsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hospitalization_ObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CreateHospitalizationButton)
                        .addGap(15, 15, 15))
                    .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                        .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                .addComponent(RequestMedicalAppointmentLabel)
                                .addGap(18, 18, 18)
                                .addGroup(RequestCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SpecialtyRadioButton)
                                    .addComponent(DoctorRadioButton))
                                .addGap(18, 18, 18)
                                .addComponent(RequestMedicalAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AppointmentDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AppointmentDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(AppointmentTimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AppointmentReasonLabel)
                                .addGap(24, 24, 24)
                                .addComponent(AppointmentReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RequestCancelPanelLayout.createSequentialGroup()
                                .addComponent(CancelAppointmentLabel)
                                .addGap(39, 39, 39)
                                .addComponent(IDAppointmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(IDAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CancelAppointmentObservationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Cancel_ObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(CancelButton)))
                        .addGap(18, 18, 18)
                        .addComponent(AppointmentTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AppointmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(CreateMedicalAppointmentButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        PatientViewTabbedPane.addTab("Request/Cancel", RequestCancelPanel);

        javax.swing.GroupLayout LayoutPanelRoundLayout = new javax.swing.GroupLayout(LayoutPanelRound);
        LayoutPanelRound.setLayout(LayoutPanelRoundLayout);
        LayoutPanelRoundLayout.setHorizontalGroup(
            LayoutPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SuperiorPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PatientViewTabbedPane)
        );
        LayoutPanelRoundLayout.setVerticalGroup(
            LayoutPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutPanelRoundLayout.createSequentialGroup()
                .addComponent(SuperiorPanelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientViewTabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayoutPanelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SuperiorPanelRoundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorPanelRoundMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_SuperiorPanelRoundMousePressed

    private void SuperiorPanelRoundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorPanelRoundMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_SuperiorPanelRoundMouseDragged

    private void ExitButtonPatientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonPatientViewActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonPatientViewActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        String id = IDAppointmentComboBox.getSelectedItem().toString();
        String observations = Cancel_ObservationsTextArea.getText();
        Response response = patientController.cancelAppointment(id, observations);
        JOptionPane.showMessageDialog(this, response.getMessage());
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        Response response = patientController.updatePatient(patient.getId(), UserTextField.getText(), FirstnameTextField.getText(), LastnameTextField.getText(), PasswordTextField.getText(), PasswordConfirmTextField.getText(), EmailTextField.getText(), BirthdateTextField.getText(), GenderComboBox.getSelectedIndex() == 1, Long.parseLong(PhoneTextField.getText()), AdressTextField.getText());
        JOptionPane.showMessageDialog(this, response.getMessage());
        clearSaveForm();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        this.setVisible(false);
        new LoginView(createLoginController()).setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        AdminView admin = new AdminView(user, users,hospitalizations, appointments);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SpecialtyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialtyRadioButtonActionPerformed
        if (DoctorRadioButton.isSelected()) {
            DoctorRadioButton.setSelected(false);
        }
        RequestMedicalAppointmentComboBox.removeAllItems();
        RequestMedicalAppointmentComboBox.addItem("Select one");
        for (String specialty : patientController.getSpecialties()) {
            RequestMedicalAppointmentComboBox.addItem(specialty);
        }
    }//GEN-LAST:event_SpecialtyRadioButtonActionPerformed

    private void DoctorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorRadioButtonActionPerformed
        if (SpecialtyRadioButton.isSelected()) {
            SpecialtyRadioButton.setSelected(false);
        }
        RequestMedicalAppointmentComboBox.removeAllItems();
        RequestMedicalAppointmentComboBox.addItem("Select one");
        for (String doctor : patientController.getDoctors()) {
            RequestMedicalAppointmentComboBox.addItem(doctor);
        }
    }//GEN-LAST:event_DoctorRadioButtonActionPerformed

    private void CreateMedicalAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMedicalAppointmentButtonActionPerformed
        boolean isSpecialty = SpecialtyRadioButton.isSelected();
        String selected = RequestMedicalAppointmentComboBox.getSelectedItem().toString();
        boolean type = AppointmentTypeComboBox.getSelectedItem().equals("In-person");
        Response response = patientController.createAppointment(AppointmentDateTextField.getText(), AppointmentTimeTextField.getText(), AppointmentReasonTextArea.getText(), isSpecialty, selected, type, (Patient) patient);
        JOptionPane.showMessageDialog(this, response.getMessage());
    }//GEN-LAST:event_CreateMedicalAppointmentButtonActionPerformed


    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) AppointmentHistory_Table.getModel();
        model.setRowCount(0);
        for (Object[] row : patientController.getPatientAppointments(patient)) {
            model.addRow(row);
        }
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void CreateHospitalizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateHospitalizationButtonActionPerformed
        Response response = hospitalizationController.requestHospitalization(patient.getId(), AttendingDoctorComboBox.getSelectedItem().toString(), EstimatedDateAdmissionTextField.getText(), HospitalizationReasonTextArea.getText(), RoomType.valueOf(DesiredRoomTypeComboBox.getSelectedItem().toString().replace(" ", "_").toUpperCase()), Hospitalization_ObservationsTextArea.getText());
        JOptionPane.showMessageDialog(this, response.getMessage());
    }//GEN-LAST:event_CreateHospitalizationButtonActionPerformed

    private void AppointmentTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppointmentTypeComboBoxActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdressLabel;
    private javax.swing.JTextField AdressTextField;
    private javax.swing.JLabel AppointmentDateLabel;
    private javax.swing.JTextField AppointmentDateTextField;
    private javax.swing.JPanel AppointmentHistoryPanel;
    private javax.swing.JScrollPane AppointmentHistory_ScrollPane;
    private javax.swing.JTable AppointmentHistory_Table;
    private javax.swing.JLabel AppointmentReasonLabel;
    private javax.swing.JScrollPane AppointmentReasonScrollPane;
    private javax.swing.JTextArea AppointmentReasonTextArea;
    private javax.swing.JLabel AppointmentTimeLabel;
    private javax.swing.JTextField AppointmentTimeTextField;
    private javax.swing.JComboBox<String> AppointmentTypeComboBox;
    private javax.swing.JLabel AppointmentTypeLabel;
    private javax.swing.JComboBox<String> AttendingDoctorComboBox;
    private javax.swing.JLabel AttendingDoctorLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BirthdateLabel;
    private javax.swing.JTextField BirthdateTextField;
    private javax.swing.JLabel CancelAppointmentLabel;
    private javax.swing.JLabel CancelAppointmentObservationLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JScrollPane Cancel_ObservationsScrollPane;
    private javax.swing.JTextArea Cancel_ObservationsTextArea;
    private javax.swing.JButton CreateHospitalizationButton;
    private javax.swing.JButton CreateMedicalAppointmentButton;
    private javax.swing.JComboBox<String> DesiredRoomTypeComboBox;
    private javax.swing.JLabel DesiredRoomTypeLabel;
    private javax.swing.JRadioButton DoctorRadioButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel EstimatedDateAdmissionLabel;
    private javax.swing.JTextField EstimatedDateAdmissionTextField;
    private javax.swing.JButton ExitButtonPatientView;
    private javax.swing.JLabel FirstnameLabel;
    private javax.swing.JTextField FirstnameTextField;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel HospitalizationObservationsLabel;
    private javax.swing.JLabel HospitalizationReasonLabel;
    private javax.swing.JScrollPane HospitalizationReasonScrollPane;
    private javax.swing.JTextArea HospitalizationReasonTextArea;
    private javax.swing.JScrollPane Hospitalization_ObservationsScrollPane;
    private javax.swing.JTextArea Hospitalization_ObservationsTextArea;
    private javax.swing.JComboBox<String> IDAppointmentComboBox;
    private javax.swing.JLabel IDAppointmentLabel;
    private javax.swing.JLabel LastnameLabel;
    private javax.swing.JTextField LastnameTextField;
    private packagee.PanelRound LayoutPanelRound;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel ModifyInfoPanel;
    private javax.swing.JLabel PasswordConfirmLabel;
    private javax.swing.JTextField PasswordConfirmTextField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JLabel PatientViewLabel;
    private javax.swing.JTabbedPane PatientViewTabbedPane;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JPanel RequestCancelPanel;
    private javax.swing.JLabel RequestHospitalizationLab;
    private javax.swing.JComboBox<String> RequestMedicalAppointmentComboBox;
    private javax.swing.JLabel RequestMedicalAppointmentLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JSeparator Separator_Hospitalization_Cancel;
    private javax.swing.JSeparator Separator_MedicalAppointment_Hospitalization;
    private javax.swing.JRadioButton SpecialtyRadioButton;
    private packagee.PanelRound SuperiorPanelRound;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UserTextField;
    // End of variables declaration//GEN-END:variables
}
